---
- name: Install required packages for Docker
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - gnupg

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

# - name: Download Docker GPG key
#   get_url:
#     url: "https://download.docker.com/linux/raspbian/gpg"
#     dest: "/etc/apt/keyrings/docker.gpg"
#     mode: "0644"
#   become: true

- name: Import Docker GPG key
  apt_key:
    keyring: "/etc/apt/trusted.gpg.d/docker.gpg"
    url: "https://download.docker.com/linux/raspbian/gpg"
  become: true

- name: Change permissions of Docker GPG key
  file:
    path: "/etc/apt/keyrings/docker.gpg"
    mode: "a+r"
  become: true

- name: Add Docker APT repository
  lineinfile:
    path: "/etc/apt/sources.list.d/docker.list"
    line: 'deb [arch="{{ ansible_architecture }}" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian bullseye stable'
    state: present
    create: yes
  become: true

- name: Update repositories
  apt:
    update_cache: yes
  become: true

- name: Install Docker Engine
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true
